//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPurse.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int ID { get; set; }
        public int AccountID { get; set; }
        public double Amount { get; set; }
        public int TransactionType { get; set; }
        public Nullable<int> AccountTransferTo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual account account { get; set; }
        public virtual trans_type trans_type { get; set; }
    }
}
